root: true
env:
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  import/resolver:
    typescript:
      alwaysTryTypes: true
rules:
  '@typescript-eslint/naming-convention': warn
  '@typescript-eslint/quotes':
    - error
    - single
    - avoidEscape: true
  '@typescript-eslint/semi':
    - error
    - never

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  comma-dangle:
    - error
    - always-multiline
  curly: warn
  eqeqeq: warn
  no-throw-literal: warn
  no-trailing-spaces: error
  quotes: 'off'
  semi: 'off'
