name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

  i18n:
    runs-on: ubuntu-latest
    # only run on pushes to master branch
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [build]
    steps:
      - name: Push Translatable Strings onto Crowdin
        run: |
          yarn port-i18n
          yarn crowdin:push
