name: Build and Package

on:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggerred by pull request comment
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '#build'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Cancel if not triggerred
        if: steps.check.outputs.triggered != 'true'
        uses: andymckay/cancel-action@0.2

      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Dependencies
        run: |
          yarn install
          yarn global add vsce js-yaml
      
      - name: Build
        run: |
          yarn run package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cactbot-highlight-build
          path: cactbot-highlight*.vsix

      - name: Add Comment when built on Pull Request
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Built success fully! You can check it out in https://github.com/MaikoTan/cactbot-highlight/actions/runs/${{ github.run_id }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
